<a href="https://colab.research.google.com/github/RamMaravilla/lab-pivot-table-and-correlation/blob/master/pivot_relationships.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas
import numpy

In [0]:
vehicles = pandas.read_csv('./vehicles.csv')

In [0]:
vehicles.pivot_table(index=['Vehicle Class'])

                                    CO2 Emission Grams/Mile  ...         Year
Vehicle Class                                                ...
Compact Cars                                     396.758088  ...  2001.097589
Large Cars                                       484.391278  ...  2004.792193
Midsize Cars                                     432.861095  ...  2002.438100
Midsize Station Wagons                           432.128533  ...  2004.108173
Midsize-Large Station Wagons                     452.981561  ...  1989.941548
Minicompact Cars                                 443.861984  ...  2004.628713
Minivan - 2WD                                    469.287896  ...  2006.380665
Minivan - 4WD                                    504.595699  ...  2005.063830
Small Pickup Trucks                              450.039261  ...  1988.938931
Small Pickup Trucks 2WD                          454.361734  ...  2001.623441
Small Pickup Trucks 4WD                          497.689565  ...  2004.840000
Small Sport Utility Vehicle 2WD                  378.034759  ...  2014.895722
Small Sport Utility Vehicle 4WD                  403.410931  ...  2014.979757
Small Station Wagons                             383.149627  ...  2001.119621
Special Purpose Vehicle                          462.727273  ...  2003.000000
Special Purpose Vehicle 2WD                      523.669366  ...  1992.359725
Special Purpose Vehicle 4WD                      562.121707  ...  1991.078125
Special Purpose Vehicles                         554.603335  ...  1991.693732
Special Purpose Vehicles/2wd                     458.456349  ...  1997.000000
Special Purpose Vehicles/4wd                     522.764706  ...  1997.000000
Sport Utility Vehicle - 2WD                      487.995241  ...  2006.261300
Sport Utility Vehicle - 4WD                      531.005884  ...  2006.257568
Standard Pickup Trucks                           605.415356  ...  1990.493726
Standard Pickup Trucks 2WD                       551.421895  ...  2003.083260
Standard Pickup Trucks 4WD                       589.712622  ...  2003.874870
Standard Pickup Trucks/2wd                       687.684524  ...  1995.000000
Standard Sport Utility Vehicle 2WD               487.407821  ...  2014.972067
Standard Sport Utility Vehicle 4WD               505.193154  ...  2014.946210
Subcompact Cars                                  414.484391  ...  1998.316187
Two Seaters                                      498.090133  ...  2003.746076
Vans                                             607.848459  ...  1989.710972
Vans Passenger                                   631.674020  ...  1992.500000
Vans, Cargo Type                                 624.214456  ...  2001.837963
Vans, Passenger Type                             648.264752  ...  2002.787375

[34 rows x 9 columns]

In [0]:
vehicles.pivot_table(index=["Vehicle Class"], columns=["Cylinders"], fill_value=0)

                                   CO2 Emission Grams/Mile  ...      Year
Cylinders                                             2.0   ...      16.0
Vehicle Class                                               ...
Compact Cars                                      0.000000  ...     0.000
Large Cars                                        0.000000  ...     0.000
Midsize Cars                                      0.000000  ...     0.000
Midsize Station Wagons                            0.000000  ...     0.000
Midsize-Large Station Wagons                      0.000000  ...     0.000
Minicompact Cars                                493.722222  ...     0.000
Minivan - 2WD                                     0.000000  ...     0.000
Minivan - 4WD                                     0.000000  ...     0.000
Small Pickup Trucks                               0.000000  ...     0.000
Small Pickup Trucks 2WD                           0.000000  ...     0.000
Small Pickup Trucks 4WD                           0.000000  ...     0.000
Small Sport Utility Vehicle 2WD                   0.000000  ...     0.000
Small Sport Utility Vehicle 4WD                   0.000000  ...     0.000
Small Station Wagons                              0.000000  ...     0.000
Special Purpose Vehicle                           0.000000  ...     0.000
Special Purpose Vehicle 2WD                       0.000000  ...     0.000
Special Purpose Vehicle 4WD                       0.000000  ...     0.000
Special Purpose Vehicles                          0.000000  ...     0.000
Special Purpose Vehicles/2wd                      0.000000  ...     0.000
Special Purpose Vehicles/4wd                      0.000000  ...     0.000
Sport Utility Vehicle - 2WD                       0.000000  ...     0.000
Sport Utility Vehicle - 4WD                       0.000000  ...     0.000
Standard Pickup Trucks                            0.000000  ...     0.000
Standard Pickup Trucks 2WD                        0.000000  ...     0.000
Standard Pickup Trucks 4WD                        0.000000  ...     0.000
Standard Pickup Trucks/2wd                        0.000000  ...     0.000
Standard Sport Utility Vehicle 2WD                0.000000  ...     0.000
Standard Sport Utility Vehicle 4WD                0.000000  ...     0.000
Subcompact Cars                                 413.718067  ...     0.000
Two Seaters                                     510.317927  ...  2011.125
Vans                                              0.000000  ...     0.000
Vans Passenger                                    0.000000  ...     0.000
Vans, Cargo Type                                  0.000000  ...     0.000
Vans, Passenger Type                              0.000000  ...     0.000

[34 rows x 72 columns]

In [0]:
vehicles.pivot_table(index=["Vehicle Class"], values=["Combined MPG"], aggfunc=numpy.mean)

                                    Combined MPG
Vehicle Class
Compact Cars                           23.373385
Large Cars                             18.936854
Midsize Cars                           21.670441
Midsize Station Wagons                 21.024038
Midsize-Large Station Wagons           19.924171
Minicompact Cars                       21.028053
Minivan - 2WD                          19.117825
Minivan - 4WD                          17.638298
Small Pickup Trucks                    20.257634
Small Pickup Trucks 2WD                19.997506
Small Pickup Trucks 4WD                18.125000
Small Sport Utility Vehicle 2WD        23.818182
Small Sport Utility Vehicle 4WD        22.421053
Small Station Wagons                   23.839533
Special Purpose Vehicle                22.000000
Special Purpose Vehicle 2WD            17.726334
Special Purpose Vehicle 4WD            16.558594
Special Purpose Vehicles               16.755698
Special Purpose Vehicles/2wd           19.500000
Special Purpose Vehicles/4wd           17.000000
Sport Utility Vehicle - 2WD            18.824149
Sport Utility Vehicle - 4WD            17.298414
Standard Pickup Trucks                 15.241887
Standard Pickup Trucks 2WD             16.542507
Standard Pickup Trucks 4WD             15.372263
Standard Pickup Trucks/2wd             13.000000
Standard Sport Utility Vehicle 2WD     18.614525
Standard Sport Utility Vehicle 4WD     18.129584
Subcompact Cars                        22.626200
Two Seaters                            19.514013
Vans                                   15.121320
Vans Passenger                         14.500000
Vans, Cargo Type                       14.377315
Vans, Passenger Type                   13.877076

In [0]:
vehicles.pivot_table(index=["Vehicle Class"], values=["Combined MPG", "CO2 Emission Grams/Mile"])

                                    CO2 Emission Grams/Mile  Combined MPG
Vehicle Class
Compact Cars                                     396.758088     23.373385
Large Cars                                       484.391278     18.936854
Midsize Cars                                     432.861095     21.670441
Midsize Station Wagons                           432.128533     21.024038
Midsize-Large Station Wagons                     452.981561     19.924171
Minicompact Cars                                 443.861984     21.028053
Minivan - 2WD                                    469.287896     19.117825
Minivan - 4WD                                    504.595699     17.638298
Small Pickup Trucks                              450.039261     20.257634
Small Pickup Trucks 2WD                          454.361734     19.997506
Small Pickup Trucks 4WD                          497.689565     18.125000
Small Sport Utility Vehicle 2WD                  378.034759     23.818182
Small Sport Utility Vehicle 4WD                  403.410931     22.421053
Small Station Wagons                             383.149627     23.839533
Special Purpose Vehicle                          462.727273     22.000000
Special Purpose Vehicle 2WD                      523.669366     17.726334
Special Purpose Vehicle 4WD                      562.121707     16.558594
Special Purpose Vehicles                         554.603335     16.755698
Special Purpose Vehicles/2wd                     458.456349     19.500000
Special Purpose Vehicles/4wd                     522.764706     17.000000
Sport Utility Vehicle - 2WD                      487.995241     18.824149
Sport Utility Vehicle - 4WD                      531.005884     17.298414
Standard Pickup Trucks                           605.415356     15.241887
Standard Pickup Trucks 2WD                       551.421895     16.542507
Standard Pickup Trucks 4WD                       589.712622     15.372263
Standard Pickup Trucks/2wd                       687.684524     13.000000
Standard Sport Utility Vehicle 2WD               487.407821     18.614525
Standard Sport Utility Vehicle 4WD               505.193154     18.129584
Subcompact Cars                                  414.484391     22.626200
Two Seaters                                      498.090133     19.514013
Vans                                             607.848459     15.121320
Vans Passenger                                   631.674020     14.500000
Vans, Cargo Type                                 624.214456     14.377315
Vans, Passenger Type                             648.264752     13.877076

In [0]:
vehicles.pivot_table(index=["Vehicle Class"], columns=["Cylinders"], values=["Combined MPG"], fill_value=0,aggfunc=numpy.std)

                                   Combined MPG            ...
Cylinders                                  2.0       3.0   ...      12.0 16.0
Vehicle Class                                              ...
Compact Cars                           0.000000  2.534609  ...  0.999068    0
Large Cars                             0.000000  0.000000  ...  1.372687    0
Midsize Cars                           0.000000  0.000000  ...  1.170615    0
Midsize Station Wagons                 0.000000  0.000000  ...  0.000000    0
Midsize-Large Station Wagons           0.000000  0.000000  ...  0.000000    0
Minicompact Cars                       0.000000  4.947679  ...  1.292298    0
Minivan - 2WD                          0.000000  0.000000  ...  0.000000    0
Minivan - 4WD                          0.000000  0.000000  ...  0.000000    0
Small Pickup Trucks                    0.000000  0.000000  ...  0.000000    0
Small Pickup Trucks 2WD                0.000000  0.000000  ...  0.000000    0
Small Pickup Trucks 4WD                0.000000  0.000000  ...  0.000000    0
Small Sport Utility Vehicle 2WD        0.000000  0.000000  ...  0.000000    0
Small Sport Utility Vehicle 4WD        0.000000  0.000000  ...  0.000000    0
Small Station Wagons                   0.000000  0.000000  ...  0.000000    0
Special Purpose Vehicle 2WD            0.000000  0.000000  ...  0.000000    0
Special Purpose Vehicle 4WD            0.000000  0.000000  ...  0.000000    0
Special Purpose Vehicles               0.000000  0.000000  ...  0.000000    0
Special Purpose Vehicles/4wd           0.000000  0.000000  ...  0.000000    0
Sport Utility Vehicle - 2WD            0.000000  0.000000  ...  0.000000    0
Sport Utility Vehicle - 4WD            0.000000  0.000000  ...  0.000000    0
Standard Pickup Trucks                 0.000000  0.000000  ...  0.000000    0
Standard Pickup Trucks 2WD             0.000000  0.000000  ...  0.000000    0
Standard Pickup Trucks 4WD             0.000000  0.000000  ...  0.000000    0
Standard Pickup Trucks/2wd             0.000000  0.000000  ...  0.000000    0
Standard Sport Utility Vehicle 2WD     0.000000  0.000000  ...  0.000000    0
Standard Sport Utility Vehicle 4WD     0.000000  0.000000  ...  2.121320    0
Subcompact Cars                        7.740302  5.040431  ...  1.693455    0
Two Seaters                            0.503953  7.407972  ...  1.874188    0
Vans                                   0.000000  0.000000  ...  0.000000    0
Vans, Cargo Type                       0.000000  0.000000  ...  0.000000    0
Vans, Passenger Type                   0.000000  0.000000  ...  0.000000    0

[31 rows x 9 columns]

In [0]:
vehicles['City MPG'].corr(vehicles['Highway MPG'])

0.92385558852884

In [0]:
vehicles.corr()

                             Year  ...  Fuel Cost/Year
Year                     1.000000  ...       -0.091913
Engine Displacement      0.037876  ...        0.769678
Cylinders                0.082469  ...        0.778153
Fuel Barrels/Year       -0.221084  ...        0.916208
City MPG                 0.161818  ...       -0.858645
Highway MPG              0.267259  ...       -0.851404
Combined MPG             0.204751  ...       -0.875185
CO2 Emission Grams/Mile -0.222300  ...        0.930865
Fuel Cost/Year          -0.091913  ...        1.000000

[9 rows x 9 columns]

In [0]:
vehicles.corr(method='spearman')

                             Year  ...  Fuel Cost/Year
Year                     1.000000  ...       -0.091437
Engine Displacement      0.051370  ...        0.794755
Cylinders                0.068727  ...        0.790481
Fuel Barrels/Year       -0.214857  ...        0.919069
City MPG                 0.157137  ...       -0.928713
Highway MPG              0.266934  ...       -0.876067
Combined MPG             0.205080  ...       -0.926078
CO2 Emission Grams/Mile -0.215108  ...        0.922723
Fuel Cost/Year          -0.091437  ...        1.000000

[9 rows x 9 columns]

In [0]:
vehicles['City MPG'].corr(vehicles['Highway MPG'], method="kendall")

0.8171408108342495

In [0]:
vehicles.corr(method='kendall')

                             Year  ...  Fuel Cost/Year
Year                     1.000000  ...       -0.064127
Engine Displacement      0.037129  ...        0.623155
Cylinders                0.053817  ...        0.668536
Fuel Barrels/Year       -0.152204  ...        0.817171
City MPG                 0.110961  ...       -0.816957
Highway MPG              0.189554  ...       -0.733986
Combined MPG             0.145378  ...       -0.824848
CO2 Emission Grams/Mile -0.151399  ...        0.814330
Fuel Cost/Year          -0.064127  ...        1.000000

[9 rows x 9 columns]